### ISSUE TITLE
list(pyecm.factors(6))

### ISSUE THREAD

**Issue by RYNO8** [martingkelly/pyecm#2]
[2, mpz(3)]
returns values with multiple types (I'm not sure if this is intended?)

also, on line 1240, kwargs might be helpful for unexperienced users
def factors(n, veb=False, ra=False, ov="dummy", pr=1):

**Comment by RYNO8** [comment]
oh btw, should pyecm.factors(0) throw a ValueError("math domain error")

**Comment by martingkelly** [comment]
Returning [2, mpz(3)] is harmless; this is because we first divide by 2 and yield the integer 2. Afterwards, we convert n to an mpz and trial divide, producing mpz(3). I'll change it to return mpz(2) just for consistency, but this won't harm anything.

Not checking for 0 is also harmless, as the frontend pyecm.py checks for 0, and pyecm is not intended to be a library program in which every routine can be imported and used standalone. However, it's easy to fix, so I will do this.

**Comment by martingkelly** [comment]
These are now fixed in master.
